kitchen/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^login', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    url(r'^logout/$',views.logout,name='logout'),
    # url(r'^cart/$',views.cart,name='cart'),
    url(r'^info/$',views.info,name='info'),
    url(r'^order/$',views.order,name='order'),
    url(r'^placeorder/$',views.placeorder,name='placeorder'),
    url(r'^site/$',views.site,name='site'),
    url(r'^detail/(?P<goodid>\w+)/$',views.detail,name='detail'),
    url(r'^cart/(?P<goodsid>\w+)/$',views.cart,name='detail'),
    url(r'^check/$', views.check, name='check'),
    url(r'^change/$', views.change, name='change'),
    url(r'^xiugai/$', views.xiugai, name='xiugai'),

]

kitchen/kitchen/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^app/', include('App.urls', namespace="app")),
]

kitchen/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.username %}
                <a href="">欢迎您：{{request.session.username}}</a>
                {% endif %}
				<div class="login_btn fl">
					<a href="/app/login/">登录</a>
					<span>|</span>
					<a href="/app/register/">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/app/info/">用户中心</a>
					<span>|</span>
					<a href="/app/cart/">我的购物车</a>
					<span>|</span>
					<a href="/app/order/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="/static/images/goods/goods012.jpg"></li>
		<li class="col03">{{ good.name }}<br><em>{{ good.price }}/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="/app/placeorder/">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

kitchen/templates/change.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.username %}
                <a href="">欢迎您：{{request.session.username}}</a>
                {% endif %}
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="user_center_info.html">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="user_center_site.html" class="active">· 收货地址</a></li>
			</ul>
		</div>

				<h3 class="common_title2">修改信息</h3>
				<div class="site_con">
					<form action="/app/change/" method="post">
                        <h3>用户名：{{request.session.username}}</h3>
						<div class="form_group">
							<label>修改密码：</label>
							<input type="text" name="password">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="city"></textarea>
						</div>
						<div class="form_group">
							<label>邮箱：</label>
							<input type="text" name="email">
						</div>
						<div class="form_group">
							<label>手机号：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



</body>
</html>

kitchen/templates/check.html
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>

天天生鲜-商品详情

    </title>

    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">



    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>




</head>
<body>

    	<div class="header_con">
		<div class="header">
			<div class="welcome fl"><a href="/goods/index/">欢迎来到天天生鲜!</a></div>
			<div class="fr">

				<div class="login_info fl" >
                    {% if request.session.username %}
                <a href="">欢迎您：{{request.session.username}}</a>
                {% endif %}
					<a href="/user/logout/">退出</a>
				</div>

				<div class="login_btn fl" >
					<a href="/user/login/">登录</a>
					<span>|</span>
					<a href="/user/register/">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="/user/user_info/">用户中心</a>
					<span>|</span>
					<a href="/cart/cart/" >我的购物车</a>
					<span>|</span>
					<a href="/order/user_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>



	<div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form action="/goods/search/" method="get">
                <input type="hidden" name="csrfmiddlewaretoken" value="ebekwMd4HXIhCTTpZYg0WWPTKROmneTYmoz4DMdP6Z7WbM00HlgkIo7jY7hbtg1T">
                <input type="text" class="input_text fl" name="key_words" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/app/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
		<script>
			$.get('/cart/cart_num/',function(data){
				if(data.code == '200'){
					$('#show_count').text(data.count)
				}
			})
		</script>
	</div>



	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/goods/list/1/" class="fruit">新鲜水果</a></li>
					<li><a href="/goods/list/2/" class="seafood">海鲜水产</a></li>
					<li><a href="/goods/list/3/" class="meet">猪牛羊肉</a></li>
					<li><a href="/goods/list/4/" class="egg">禽类蛋品</a></li>
					<li><a href="/goods/list/5/" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/goods/list/6/" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="" onclick="app()">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="" onclick="app()">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="/goods/index/">全部分类</a>
		<span></span>


		<a href="/goods/list/1/">
				新鲜水果
		</a>












		<span></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
        {% for goo in good %}
		<div class="goods_detail_pic fl"><img src="{{ goo.pic }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goo.name }}</h3>
			<p>无</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em class="show_pirze1">{{ goo.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
         {% endfor %}
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a onclick="add_goods()" href="javascript:;" class="add fr">+</a>
					<a onclick="sub_goods()" href="javascript:;" class="minus fr">-</a>
				</div>
				<script>
				function add_goods(){
					var num = $('.num_show').val()
					var price = parseInt($('.show_pirze1').text())
					var new_num = parseInt(num) + 1
					$('.num_show').val(new_num)
					total = new_num * price
					$('#price').text(total)
				}

				function sub_goods(){
					var num = $('.num_show').val()
					var price = parseInt($('.show_pirze1').text())
					if(parseInt(num) > 1){
						var new_num = parseInt(num) - 1
						$('.num_show').val(new_num)
						total = new_num * price
						$('#price').text(total)
					}
				}

				</script>
			</div>
			<div class="total">总价：<em id="price">1.0</em>元</div>
			<div class="operate_btn">
{#				<a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="">购物车</a>
{#			    <a onclick="add_cart(7)"
				   href="javascript:;"
				   class="add_cart"
				   id="add_cart">
					加入购物车
				</a>
			</div>
			</div>
            <input type="hidden" name="csrfmiddlewaretoken" value="ebekwMd4HXIhCTTpZYg0WWPTKROmneTYmoz4DMdP6Z7WbM00HlgkIo7jY7hbtg1T">

		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>

					<li>
						<a href="/goods/detail/7/"><img src="/media/goods/images/goods003_ctorEWk.jpg"></a>
						<h4><a href="/goods/detail/7/">草莓</a></h4>
						<div class="prize">￥1.0</div>
					</li>

					<li>
						<a href="/goods/detail/9/"><img src="/media/goods/images/goods002_84wwc2I.jpg"></a>
						<h4><a href="/goods/detail/9/">葡萄</a></h4>
						<div class="prize">￥10.0</div>
					</li>

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>
			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>None</dd>
				</dl>
			</div>

		</div>
	</div>




    	<div class="footer">
		<div class="foot_link">
			<a href="" onclick="none()">关于我们</a>
			<span>|</span>
			<a href="" onclick="none()">联系我们</a>
			<span>|</span>
			<a href="" onclick="none()">招聘人才</a>
			<span>|</span>
			<a href="" onclick="none()">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script>
		function none(){
			alert('暂不开放，滚')
			location.reload
		}

	</script>

<div class="add_jump"></div>




	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;
		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
                        <!--window.locaion.reload()-->
					});
			});
		})
	</script>

</body>
</html>

kitchen/templates/index.html

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-首页</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.username %}
                 <div class="user_link fl">
                <a href="/app/info/">欢迎您：{{request.session.username}}</a>

                <span>|</span>
				<a href="/app/logout/">退出</a>
                <span>|</span>
                <a href="/app/info/">用户中心</a>
                <span>|</span>
                <a href="/app/cart/">我的购物车</a>
                <span>|</span>
					<a href="/app/order/">我的订单</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="/app/login/">登录</a>
                <span>|</span>
                <a href="/app/register/">注册</a>
            </div>
            {% endif %}
			</div>
		</div>
	</div>
    <div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form class="form-inline" action="{% url 'app:check' %}" method="POST">
            <div class="search_con fr">
                <input type="text" class="input_text fl" name="check" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </div>
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
		<script>
			$.get('/cart/cart_num/',function(data){
				if(data.code == '200'){
					$('#show_count').text(data.count)
				}
			})
		</script>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="index.html">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for i in type %}
			<li><a href="#{{ i.id}}" class="fruit">{{ i.ttitle }}</a></li>
            {% endfor %}
{#			<li><a href="#model02" class="seafood">海鲜水产</a></li>#}
{#			<li><a href="#model03" class="meet">猪牛羊肉</a></li>#}
{#			<li><a href="#model04" class="egg">禽类蛋品</a></li>#}
{#			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>#}
{#			<li><a href="#model06" class="ice">速冻食品</a></li>#}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
    {% for i in type %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="{{ i.id }}">{{ i.ttitle }}</h3>
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="/app/detail/">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
                {% for j in sp %}

                {% if j.titleid == i.id %}
				<li>
                    <a href="{% url 'app:detail' goodid=j.id %}" class="link">
					<h4><a href="{% url 'app:detail' goodid=j.id %}">{{ j.name }}</a></h4>
					<a href="{% url 'app:detail' goodid=j.id %}"><img src="{{ j.pic }}"></a>
					<div class="prize">￥ {{ j.price }}</div>
                    </a>
				</li>
                {% endif %}
                {% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight ? 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/js/slide.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

kitchen/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/app/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/app/login/" method="POST">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="/app/register/">忘记密码</a>
							<a href="/app/index/">登录</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>

	
</body>
</html>

kitchen/templates/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-提交订单</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.username %}
                <a href="">欢迎您：{{request.session.username}}</a>
                {% endif %}
				<div class="login_btn fl">
					<a href="/app/login/">登录</a>
					<span>|</span>
					<a href="/app/register/">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/app/info/">用户中心</a>
					<span>|</span>
					<a href="/app/cart/">我的购物车</a>
					<span>|</span>
					<a href="/app/order/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">1</li>			
			<li class="col02"><img src="/static/images/goods/goods012.jpg"></li>
			<li class="col03">奇异果</li>
			<li class="col04">500g</li>
			<li class="col05">25.80元</li>
			<li class="col06">1</li>
			<li class="col07">25.80元</li>	
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">2</li>			
			<li class="col02"><img src="/static/images/goods/goods003.jpg"></li>
			<li class="col03">大兴大棚草莓</li>
			<li class="col04">500g</li>
			<li class="col05">16.80元</li>
			<li class="col06">1</li>
			<li class="col07">16.80元</li>	
		</ul>
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'index.html';
					});	
				},3000)
				
			});
		});
	</script>
</body>
</html>